# Generated by Django 4.2.7 on 2026-02-01 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokerTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('max_players', models.IntegerField(default=6)),
                ('small_blind', models.IntegerField(default=10)),
                ('big_blind', models.IntegerField(default=20)),
                ('ante', models.IntegerField(default=0)),
                ('initial_chips', models.IntegerField(default=1000)),
                ('time_limit_seconds', models.IntegerField(default=30)),
                ('allow_mid_entry', models.BooleanField(default=True)),
                ('allow_mid_exit', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('waiting', '待機中'), ('playing', 'プレイ中'), ('finished', '終了')], default='waiting', max_length=20)),
                ('current_hand_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TablePlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('seat_number', models.IntegerField()),
                ('chips', models.IntegerField(default=1000)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_players', to='poker.pokertable')),
            ],
            options={
                'unique_together': {('table', 'seat_number'), ('table', 'username')},
            },
        ),
        migrations.CreateModel(
            name='GameHand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hand_number', models.IntegerField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('button_seat', models.IntegerField()),
                ('total_pot', models.IntegerField(default=0)),
                ('community_cards', models.JSONField(default=list)),
                ('winner_seats', models.JSONField(default=list)),
                ('winning_hand', models.CharField(blank=True, max_length=100)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hands', to='poker.pokertable')),
            ],
            options={
                'unique_together': {('table', 'hand_number')},
            },
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('join', '参加'), ('leave', '退出'), ('post_blind', 'ブラインド'), ('post_ante', 'アンティ'), ('fold', 'フォールド'), ('check', 'チェック'), ('call', 'コール'), ('bet', 'ベット'), ('raise', 'レイズ'), ('all_in', 'オールイン'), ('deal', '配布'), ('showdown', 'ショーダウン'), ('win', '勝利')], max_length=20)),
                ('amount', models.IntegerField(default=0)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='poker.gamehand')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='poker.tableplayer')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='poker.pokertable')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
